added remove game action
tshenin/spiel-mit-bot pull request #4
Opened 2023-11-26 13:26 UTC by RadionovAleksandr

2023-11-26 22:46 UTC, tshenin requested changes

2023-11-26 22:46 UTC, tshenin commented on src/main.ts
> +  if (isAdmin(ctx.update.message.from.username)) {
я думаю надо айдишники юзать, username можно поменять в любой момент

2023-11-26 22:46 UTC, tshenin commented on src/markup/buttons.ts
> +export const adminButtons = (game: GameDocument) => ([Markup.button.callback('Удалить', `remove_game__${game.id}`)]);
`removeGameButtons`

В случае если там могут быть какие-то еще кнопки то можно назвать `renderAdminGameButtons` чет такое

2023-11-26 22:46 UTC, tshenin commented on src/markup/buttons.ts
> +      Markup.button.callback(yes, `${key}yes`),
прикольно.

Я бы постфикс лучше бы здесь писал `__yes`, `__no`.

2023-11-26 22:46 UTC, tshenin commented on src/markup/buttons.ts
>    }
давай юзать встроенные `dateFns` методы.

Ну и можно немног упростить
```typescript
export const renderDateButtons = (startDate: Date = new Date(), days: number = 7) => {
  const format = 'dd.MM.yyyy';
  const dateButtons = new Array(days)
    .fill(startDate)
    .map((startDate, index) => {
      const date = add(startDate, { days: index });
      const formattedDate = format(date, format);
      return Markup.button.callback(formattedDate, `date_enter__${formattedDate}`)
    });
  
  return { ...Markup.inlineKeyboard(dateButtons) };
}
```

2023-11-26 22:46 UTC, tshenin commented on src/markup/messages.ts
> +  message += `уровень: <b>${game.level}</b>\n`;
Уровень

2023-11-26 22:46 UTC, tshenin commented on src/scenes/game/create-game.scene.ts
> +  echoScene.enter(ctx => ctx.reply("Выберите число", {
"Выберите день"?

2023-11-26 22:46 UTC, tshenin commented on src/scenes/game/create-game.scene.ts
>    echoScene.action(/date_enter__(.+)/, (ctx) => {
`echoScene` => `createGameScene`

2023-11-26 22:46 UTC, tshenin commented on src/scenes/game/create-game.scene.ts
> +    let message = `Дата: ${date.getDate()}.${date.getMonth()} ${date.getHours()}:00\n`;
надо юзать константы и date-fns `format`

2023-11-26 22:46 UTC, tshenin commented on src/scenes/game/create-game.scene.ts
> +    message = message + `Численность: ${capacity}\n`
участников, игроков.

2023-11-26 22:46 UTC, tshenin commented on src/scenes/game/create-game.scene.ts
>    // todo coach это тот кто создает игру
⚠️ ой ей вот это так не надо делать  ⚠️ 

Этот файл глобально выполняется для всех пользователей. Тобишь любой кто может зайти в эту сцену перезапишет эти переменные.

Эти промежуточные данные надо хранить в сессии сцены.

```
let date: Date;
let coach: string;
let capacity: number;
let type: GameType;
let level: GameLevel;
```

2023-11-26 22:46 UTC, tshenin commented on src/scenes/game/remove-game.scene.ts
> +    let gameId: string;
то же семое

2023-11-26 22:46 UTC, tshenin commented on src/scenes/game/remove-game.scene.ts
> +            ...renderYesNoButtons(['Подтвердить', 'Отмена'],'remove_btn__' ),
почему `btn`?
`remove_game_confirmation` может быть?

2023-11-26 22:46 UTC, tshenin commented on src/scenes/game/show-games.scene.ts
> +      const adminCommands = isAdmin ? adminButtons(game) : [];
adminButtons

2023-11-26 22:46 UTC, tshenin commented on src/scenes/game/show-games.scene.ts
> +      if (isAdmin(ctx.update['message']?.from.username)) {
Два раза проверяешь на админа, можно в этом if так же и кнопки рендерить.

```typescript
if (isAdmin(...)) {
  const adminButtons = renderAdminGameButtons();
  buttons.push(...adminButtons);
}
```

2023-11-26 22:46 UTC, tshenin commented on src/services/utils.ts
> +export const isAdmin = (username) => process.env.ADMINS.includes(username);
лучше конечно по айдишникам проверять, да или вообще в базу записать
так как юзернейм можно поменять

2023-11-30 09:36 UTC, RadionovAleksandr commented on src/scenes/game/create-game.scene.ts
>    // todo coach это тот кто создает игру
Поправил

2023-11-30 09:37 UTC, RadionovAleksandr commented on src/scenes/game/create-game.scene.ts
> +  echoScene.enter(ctx => ctx.reply("Выберите число", {
+

2023-11-30 11:28 UTC, tshenin approved these changes

2023-11-30 11:28 UTC, tshenin commented on src/scenes/game/create-game.scene.ts
>    // todo показать кнопки времени
можно удалить теперь тудушки

2023-11-30 11:28 UTC, tshenin commented on src/scenes/game/remove-game.scene.ts
> +        if (ctx.match.at(1) === 'yes') {
А это будет работать если ты добавит `__`?

2023-12-01 04:55 UTC, merged