Game notify
tshenin/spiel-mit-bot pull request #7
Opened 2023-12-08 05:34 UTC by RadionovAleksandr

2023-12-11 13:24 UTC, tshenin requested changes

2023-12-11 13:24 UTC, tshenin commented on src/main.ts
> +  await runGameNotify(ctx);
А зачем запускать его каждый раз как кто-то начинает бота?

2023-12-11 13:24 UTC, tshenin commented on src/services/bot.service.ts
проверь плиз отступы везде, они у тебя слишком большие. 

Я вроде добавлял гит хук, но чет видимо не срабатывает.

2023-12-11 13:24 UTC, tshenin commented on src/services/bot.service.ts
> +let gameNotify;
`gameNotifier`

2023-12-11 13:24 UTC, tshenin commented on src/services/bot.service.ts
> +export const runGameNotify = async (ctx) => {
`runGameNotifier`

2023-12-11 13:24 UTC, tshenin commented on src/services/bot.service.ts
> +    const games = await getGames();
так ты получается один раз только игры получаешь, когда функцию запускаешь.
То есть новые игры сюда уже не попадут

2023-12-11 13:24 UTC, tshenin commented on src/services/bot.service.ts
> +                if (date.getTime() < new Date().getTime() + HOUR) {
плиз, давай юзать функции date-fns

2023-12-11 13:24 UTC, tshenin commented on src/services/bot.service.ts
> +    const HAF_HOUR = 180000;
HALF

2023-12-11 13:24 UTC, tshenin commented on src/services/bot.service.ts
> +                        `${dateFormated} начинется тренировка, удачной игры`
начинается? начнется?

2023-12-11 13:24 UTC, tshenin commented on src/scenes/game/create-game.scene.ts
> +      const date = new Date(new Date(year, month - 1, dayOfMonth).setHours(time));
давай юзать date-fns

2024-01-04 16:49 UTC, RadionovAleksandr commented on src/services/bot.service.ts
> +let gameNotify;
done

2024-01-04 16:49 UTC, RadionovAleksandr commented on src/services/bot.service.ts
> +export const runGameNotify = async (ctx) => {
done

2024-01-04 16:49 UTC, RadionovAleksandr commented on src/services/bot.service.ts
> +    const games = await getGames();
done

2024-01-04 16:49 UTC, RadionovAleksandr commented on src/services/bot.service.ts
> +                if (date.getTime() < new Date().getTime() + HOUR) {
done

2024-01-04 16:50 UTC, RadionovAleksandr commented on src/services/bot.service.ts
> +    const HAF_HOUR = 180000;
done

2024-01-04 16:50 UTC, RadionovAleksandr commented on src/services/bot.service.ts
> +                        `${dateFormated} начинется тренировка, удачной игры`
done

2024-01-04 16:50 UTC, RadionovAleksandr commented on src/scenes/game/create-game.scene.ts
> +      const date = new Date(new Date(year, month - 1, dayOfMonth).setHours(time));
done, получилось почти то же самое

2024-01-08 12:59 UTC, tshenin approved these changes

2024-01-09 05:56 UTC, merged